#!/usr/bin/env python3
"""Rebuilds media.js from the photos and videos in zahra_asim/highlights.

Run this from the site folder whenever you add or remove files:
    python3 build_manifest.py
"""
import json
import os
import re
import unicodedata
from urllib.parse import quote

HERE = os.path.dirname(os.path.abspath(__file__))
MEDIA_ROOT = "zahra_asim/highlights"
IMAGE_EXT = {".jpg", ".jpeg", ".png", ".webp", ".gif"}
VIDEO_EXT = {".mp4", ".mov", ".webm", ".m4v"}


def pretty_album(folder):
    # "02 𝒲𝒶𝓁ℯ𝓈" -> "Wales", "07 ‘25" -> "2025"
    name = re.sub(r"^\d+\s*", "", unicodedata.normalize("NFKC", folder)).strip()
    m = re.fullmatch(r"[‘'’](\d{2})", name)
    return f"20{m.group(1)}" if m else name


# Files listed in excluded.txt (paths relative to zahra_asim/highlights) are skipped.
excluded = set()
ex_path = os.path.join(HERE, "excluded.txt")
if os.path.exists(ex_path):
    with open(ex_path, encoding="utf-8") as fh:
        excluded = {unicodedata.normalize("NFC", l.strip()) for l in fh
                    if l.strip() and not l.startswith("#")}

items = []
base = os.path.join(HERE, MEDIA_ROOT)
for folder in sorted(os.listdir(base)):
    path = os.path.join(base, folder)
    if not os.path.isdir(path):
        continue
    for f in sorted(os.listdir(path)):
        ext = os.path.splitext(f)[1].lower()
        if ext not in IMAGE_EXT | VIDEO_EXT:
            continue
        if unicodedata.normalize("NFC", f"{folder}/{f}") in excluded:
            continue
        rel = "/".join([MEDIA_ROOT, unicodedata.normalize("NFC", folder), f])
        date = re.search(r"(\d{4}-\d{2}-\d{2})", f)
        items.append({
            "src": quote(rel),
            "type": "video" if ext in VIDEO_EXT else "image",
            "album": pretty_album(folder),
            "date": date.group(1) if date else "",
        })

with open(os.path.join(HERE, "media.js"), "w", encoding="utf-8") as out:
    out.write("// Generated by build_manifest.py — re-run it after adding files.\n")
    out.write("window.MEDIA = ")
    json.dump(items, out, ensure_ascii=False, indent=0)
    out.write(";\n")

print(f"Wrote media.js with {len(items)} items "
      f"({sum(i['type'] == 'image' for i in items)} photos, "
      f"{sum(i['type'] == 'video' for i in items)} videos)")
